# Generated by Django 6.0 on 2026-01-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dpo', 'DPO'), ('collector', 'Collector'), ('department', 'Department')], max_length=20),
        ),
    ]
