# Generated by Django 6.0 on 2026-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('dpo', 'dpo'), ('collector', 'collector'), ('department', 'department')], max_length=20),
        ),
    ]
