# Generated by Django 6.0 on 2026-01-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(max_length=300),
        ),
    ]
