# Generated by Django 6.0 on 2026-02-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_issue_issue_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='minutes/'),
        ),
    ]
