# Generated by Django 6.0.1 on 2026-02-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_minutes_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='issue_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.issuedepartment'),
        ),
    ]
