# Generated by Django 6.0 on 2026-02-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_notification_issue_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
