# Generated by Django 6.0 on 2026-02-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_issue_issue_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='parent_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='api.issue'),
        ),
    ]
