# Generated by Django 6.0 on 2026-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_issue_parent_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_status',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved')], default='unresolved', max_length=20),
        ),
    ]
