# Generated by Django 6.0 on 2026-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_department_designation_and_drop_legacy_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
    ]
