# Generated by Django 6.0 on 2026-03-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_department_created_at_department_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='attachment_path',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
    ]
