# Generated by Django 6.0 on 2026-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_response_attachment_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='attachment_path',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
